### ISSUE TITLE
REMOVE THE "DELETE ALL" OPTION FOR DELETING PEOPLE THATS DUMB

### ISSUE THREAD

**Issue by Dynam8** [Dynam8/GroupEmailerToOtherUnionTeammembers#14]
Dude, being able to delete people is good, BUT WHY WOULD YOU GIVE SOMEONE AN OPTION TO DELETE EVERYONE AT ONCE????

Just get rid of that button dude, it's not a good idea.

**Comment by Ashwin51** [comment]
Big Dumb

**Comment by fredderf121** [comment]
OMG I CANT BELIEVE YOU'RE TELLING ME THIS BUT OK I DELETED IT
